name: "Frogbot Scan Pull Request"
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/frogbot@v2
        env:
          # [Mandatory]
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_URL: ${{ secrets.JF_URL }}
          JF_WATCH: source_watch
          JF_DEPS_REPO: "npm-curated-remote"