name: "JFrog Integration Example"

on:
  push:
    branches: [ main ]
  workflow_dispatch:
#env:
  #JF_BUILD_NAME: ejs-frog-demo-build
  #JF_BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Setup Node npm
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set CLI npm Config
        run: |
          jf npm-config --global=true \
            --repo-resolve=npm-curated-remote \
            --repo-deploy=npm-local
        # Configures .npmrc globally to resolve and publish through Artifactory

      - name: Install Dependencies
        run: jf npm install
        # Downloads dependencies and attaches to build info

      - name: Publish Package to Artifactory
        run: jf npm publish
        # Upload the packeges to Artifactory

##    - name: Collect and Publish Build Info With JFrog CLI
##      run: |
##        jf rt build-collect-env
##        jf rt build-add-git
##        jf rt build-publish
        # Captures environment and git metadata, and publishes build info to Artifactory

      - name: Scan Build with Xray
        run: jf bs --vuln --fail=false
