name: "github-ejs-build"
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install prerequisites
      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
            JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: NPM Audit 
        env:
          JFROG_CLI_BUILD_NAME: 'gh-ejs-demo'
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
        run: |
          jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER 
          jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }} $GITHUB_RUN_NUMBER
          jf npmc --repo-resolve npm-curated-remote
          jf npm i --omit dev --build-name=${{ env.JFROG_CLI_BUILD_NAME }} --build-number=$GITHUB_RUN_NUMBER
          jf audit --npm
      - name: Docker build 
        env:
          JFROG_CLI_BUILD_NAME: 'gh-ejs-demo'
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
          JF_HOST: ${{ secrets.JF_HOST }}
        run: |
          docker build --build-arg JF_TOKEN=${JF_ENV_1} . -t ejs-demo:$GITHUB_RUN_NUMBER
          docker tag ejs-demo:$GITHUB_RUN_NUMBER $JF_HOST/dro-backend-docker-dev-local/ejs-demo:$GITHUB_RUN_NUMBER
          jf docker push $JF_HOST/dro-backend-docker-dev-local/ejs-demo:$GITHUB_RUN_NUMBER --build-name=$JFROG_CLI_BUILD_NAME --build-number=$GITHUB_RUN_NUMBER 
          jf rt bp $JFROG_CLI_BUILD_NAME $GITHUB_RUN_NUMBER
